In [1]:
import pandas as pd
from scipy.sparse import lil_matrix
import scipy.spatial.distance

In [2]:
stats = pd.read_csv('Full_NFL_Stats_2022.csv')

In [3]:
stats.head()

,Unnamed: 0,teamName,displayName,description,abbreviation,value,perGameValue,rank
0,0,Falcons,Fumbles,The number of times a player/team has fumbled ...,FUM,21.0,1.0,13.0
1,1,Falcons,Fumbles Lost,The number of times a fumble is recovered by t...,LST,12.0,NaN,4.0
2,2,Falcons,Forced Fumbles,The total number of forced fumbles.,FF,8.0,NaN,62.0
3,3,Falcons,Fumbles Recovered,The number of fumbles recovered.,FR,7.0,NaN,23.0
4,4,Falcons,Fumbles Touchdowns,The number of times a fumbles is recovered and...,FTD,1.0,NaN,8.0

In [4]:
stats.groupby('teamName')

In [5]:
stats.sort_values('rank',ascending=True)

,Unnamed: 0,teamName,displayName,description,abbreviation,value,perGameValue,rank
5242,27,Jets,Team Games Played,The amount of games played.,TGP,17.000000,NaN,1.0
7100,15,Seahawks,One Point Safeties Made,One Point Safeties Made,OPSM,0.000000,NaN,1.0
4568,1,Patriots,Defensive Fumble Return Yards,The amount of total yardage from fumble returns.,DFRYDS,0.000000,NaN,1.0
4567,0,Patriots,Defensive Fumbles Returns,The number of fumble returns.,DFR,0.000000,NaN,1.0
4563,39,Patriots,Team Games Played,The numbers of team games played.,GP,17.000000,NaN,1.0
...,...,...,...,...,...,...,...,...
6352,41,Chargers,Net Yards Per Pass Attempt,The average number net yards (taking sack yard...,NYDS/PA,6.112000,6.255814,NaN
7174,41,Buccaneers,Net Yards Per Pass Attempt,The average number net yards (taking sack yard...,NYDS/PA,5.932730,5.977778,NaN
7448,41,Commanders,Net Yards Per Pass Attempt,The average number net yards (taking sack yard...,NYDS/PA,5.767442,6.000000,NaN
7722,41,Panthers,Net Yards Per Pass Attempt,The average number net yards (taking sack yard...,NYDS/PA,6.077079,6.285714,NaN
7996,41,Jaguars,Net Yards Per Pass Attempt,The average number net yards (taking sack yard...,NYDS/PA,6.344551,6.444444,NaN

In [6]:
stats.dropna(subset='rank',inplace=True)

In [7]:
stats.sort_values('rank',ascending=True)

,Unnamed: 0,teamName,displayName,description,abbreviation,value,perGameValue,rank
5242,27,Jets,Team Games Played,The amount of games played.,TGP,17.000000,NaN,1.0
7100,15,Seahawks,One Point Safeties Made,One Point Safeties Made,OPSM,0.000000,NaN,1.0
4568,1,Patriots,Defensive Fumble Return Yards,The amount of total yardage from fumble returns.,DFRYDS,0.000000,NaN,1.0
4567,0,Patriots,Defensive Fumbles Returns,The number of fumble returns.,DFR,0.000000,NaN,1.0
4563,39,Patriots,Team Games Played,The numbers of team games played.,GP,17.000000,NaN,1.0
...,...,...,...,...,...,...,...,...
6353,42,Chargers,Quarterback Rating,Quarterback Rating.,RAT,93.334990,90.188423,102.0
7175,42,Buccaneers,Quarterback Rating,Quarterback Rating.,RAT,89.777500,85.675766,106.0
7156,23,Buccaneers,Passer Rating,Passer Rating,RTG,89.777500,85.675766,106.0
4964,23,Giants,Passer Rating,Passer Rating,RTG,91.111664,92.513611,114.0
4983,42,Giants,Quarterback Rating,Quarterback Rating.,RAT,91.111664,92.513611,114.0

In [8]:
stats.drop(columns=['perGameValue', 'Unnamed: 0'],axis=1, inplace=True)

In [9]:
rows = stats.loc[stats['rank'] > 32]
print(rows)

     teamName            displayName                           description  \
2     Falcons         Forced Fumbles   The total number of forced fumbles.
32    Falcons          Passer Rating                         Passer Rating
35    Falcons   Net Passing Attempts                 Net Passing Attempts.
37    Falcons  Total Offensive Plays  The number of total offensive plays.
51    Falcons     Quarterback Rating                   Quarterback Rating.
...       ...                    ...                                   ...
8271   Ravens     Quarterback Rating                   Quarterback Rating.
8331   Ravens         Assist Tackles     The number of assists on tackles.
8353   Ravens          Total Tackles          The total number of tackles.
8526   Texans          Passer Rating                         Passer Rating
8545   Texans     Quarterback Rating                   Quarterback Rating.

     abbreviation        value  rank
2              FF     8.000000  62.0
32            RTG    87.693340  79.0
35           NATT   452.000000  52.0
37            TOP  1011.000000  53.0
51            RAT    87.693340  79.0
...           ...          ...   ...
8271          RAT    82.526665  79.0
8331          AST   380.000000  51.0
8353          TOT  1147.000000  78.0
8526          RTG    76.791664  79.0
8545          RAT    76.791664  79.0

[150 rows x 6 columns]

In [10]:
interceptions = stats.loc[stats['displayName'] == 'Interception Percentage']
interceptions = interceptions.sort_values(by='rank')

In [11]:
completion = stats.loc[stats['displayName'] == 'Completion Percentage']
completion = completion.sort_values(by='rank')

In [12]:
pass_rating = stats.loc[stats['displayName'] == 'Passer Rating']
pass_rating = pass_rating.sort_values(by='value',ascending=False)

In [20]:
touchdowns = stats.loc[stats['abbreviation'] == 'TD%']
touchdowns = touchdowns.drop('rank',axis=1)
touchdowns = touchdowns.sort_values(by='value',ascending=False)

,teamName,displayName,description,abbreviation,value
3040,Chiefs,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,6.298
300,Bills,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,6.098
6602,49ers,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,5.859
848,Bengals,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,5.738
6876,Seahawks,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,5.236
3862,Dolphins,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,5.137
574,Bears,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,5.040
1396,Cowboys,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,5.036
1944,Lions,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,4.932
2218,Packers,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,4.796
3314,Raiders,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,4.778
4684,Saints,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,4.688
5506,Eagles,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,4.664
4136,Vikings,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,4.464
7424,Commanders,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,4.332
7972,Jaguars,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,4.195
26,Falcons,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,4.096
8246,Ravens,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,3.893
6328,Chargers,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,3.657
4410,Patriots,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,3.519
1122,Browns,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,3.519
2492,Titans,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,3.509
7698,Panthers,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,3.501
7150,Buccaneers,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,3.462
8520,Texans,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,3.454
4958,Giants,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,3.269
1670,Broncos,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,3.152
3588,Rams,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,3.013
2766,Colts,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,2.815
5780,Cardinals,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,2.560
5232,Jets,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,2.392
6054,Steelers,Passing Touchdown %,The percentage of passes that result in a touc...,TD%,2.102

In [14]:
pass_yard_per_game = stats.loc[stats['displayName'] == 'Passing Yards Per Game']
pass_yard_per_game = pass_yard_per_game.sort_values(by='rank',ascending=True)

In [15]:
bottom_qb = []

for df in [interceptions, completion, pass_rating, touchdowns, pass_yard_per_game]:

    bottom_names = list(df['teamName'].tail(16))

    bottom_qb += bottom_names

name_counts = {name: bottom_qb.count(name) for name in set(bottom_qb)}

final_names = [name for name in name_counts.keys() if name_counts[name] == 5]

print(final_names)

['Texans', 'Ravens', 'Steelers', 'Panthers']

In [16]:
qbsim = pd.read_csv('QBData.csv')

In [21]:
qbsim.head()

,Unnamed: 0,playerName,completionPct,completions,ESPNQBRating,interceptionPct,interceptions,longPassing,netPassingYards,netPassingYardsPerGame,...,totalTouchdowns,totalYards,twoPointPassConvs,twoPtPass,twoPtPassAttempts,yardsPerCompletion,yardsPerGame,yardsPerPassAttempt,netYardsPerPassAttempt,QBR
0,0,Patrick Mahomes,67.129997,435.0,7760.0,1.852,12.0,67.0,5062.0,297.764709,...,45.0,5614.0,-1.0,2.0,3.0,12.069,330.235291,8.102,7.510386,77.57
1,1,Justin Herbert,68.239998,477.0,6189.0,1.431,10.0,55.0,4533.0,266.647064,...,25.0,4876.0,-1.0,1.0,1.0,9.935,286.823517,6.780,6.150611,59.64
2,2,Tom Brady,66.848999,490.0,6174.0,1.228,9.0,63.0,4534.0,266.705872,...,26.0,4693.0,-1.0,2.0,6.0,9.580,276.058838,6.404,6.005298,52.50
3,3,Kirk Cousins,65.941002,424.0,6157.0,2.177,14.0,66.0,4218.0,248.117645,...,31.0,4644.0,-1.0,3.0,4.0,10.724,273.176483,7.072,6.121916,51.76
4,4,Joe Burrow,68.317001,414.0,6565.0,1.980,12.0,60.0,4216.0,263.500000,...,40.0,4732.0,-1.0,3.0,5.0,10.809,295.750000,7.384,6.516229,56.97

In [17]:
qbsimdex_df = qbsim.set_index('playerName')

In [18]:
t_player = 'Patrick Mahomes'
t_player_stat = qbsimdex_df.loc[t_player]
dist = scipy.spatial.distance.cdist(qbsimdex_df, [t_player_stat], metric = "cosine")[:,0]
query_distances = list(zip(qbsim.index, dist))

In [19]:
for sim_play, sim_stats in sorted(query_distances, key = lambda x: x[1], reverse = False)[:11]:
    print(qbsim['playerName'].iloc[sim_play], sim_stats)

Patrick Mahomes 0.0
Jared Goff 0.0004178550239457568
Joe Burrow 0.0007408481267762168
Aaron Rodgers 0.0008721264188339406
Jimmy Garoppolo 0.0011247847253029741
Trevor Lawrence 0.001368057880657747
Justin Herbert 0.0015854770383781913
Andy Dalton 0.0019217969988605255
Tom Brady 0.002044812190321821
Derek Carr 0.002723032637271139
Dak Prescott 0.002765972516346915